### ISSUE TITLE
when i use this repo to build my dqn when import SC2CollectMineralShards-v0

### ISSUE THREAD

**Issue by miqianmimi** [vwxyzjn/SC2AI#1]
there is a bug that called:
gym.error.UnregisteredEnv: No registered env with id: SC2CollectMineralShards-v0

when i run sc2_dqn .py even though i have already installed the sc2gym package

**Comment by vwxyzjn** [comment]
Please install docker and execute `docker run vwxyzjn/sc2ai:0.1.0` to fully reproduce my work. If you want the details of my build, the steps in https://github.com/vwxyzjn/SC2AI/blob/master/Dockerfile could be helpful.

**Comment by miqianmimi** [comment]
May i ask that what's the tensorboard version of this model cause my computer doesn't have enough space for the docker mirror.Thank you so much.

AttributeError: 'MultiDiscrete' object has no attribute 'nvec'

**Comment by vwxyzjn** [comment]
@miqianmimi I don’t think tensor board is part of this project.
